### ISSUE TITLE
Webforms R&D project

### ISSUE THREAD

**Issue by kardan** [akvo/isco#12]
Placeholder issue

**Comment by valllllll2000** [comment]
Here is the code https://github.com/akvo/webform-test-rjsf

**Comment by valllllll2000** [comment]
The goal of the task was to examine any possible substitutes for our webforms library.
The problem of webforms seems to be that it is tightly coupled to each implementation of forms in each project and it is not possible to merge them all. Beyond chocolate has its own implementation and other tech consultancy projects have conflicting changes as it is customized according to the needs of each project but also strongly depends on flow.

We are looking for a library to draw the webforms using React that we could integrate in our future projects and reuse without having to reinvent the wheel.
Step 1: List of candidates
https://docs.google.com/spreadsheets/d/1eoqjY8STQdlob7lV9yaKJnolw0ru3V21peRbVRfBXZ4/edit#gid=0
As per the file we examined 11 possible candidates and checked a certain number of features 
Step 2: 2 Possible candidates selected
* JsonForms: https://jsonforms.io/
* RJSF: https://github.com/rjsf-team/react-jsonschema-form

We tested them both with several examples of implementations of sample questions
We then decided to use JsonForms.

Step 3: It turned out JsonForms could not be the right candidate as beside the docs and example are not good enough, there are lot of issues that should be resolved before using it.

**Final decision: RJSF**
