### ISSUE TITLE
setup copying functionality for question, question group

### ISSUE THREAD

**Issue by joycarpediem** [akvo/isco#67]

**Comment by joycarpediem** [comment]
Optional :
Copy questionnaire

**Comment by dedenbangkit** [comment]
And what about dependency, and othet fields? Or this just copy questionnaire text, type and option @joycarpediem ?

**Comment by joycarpediem** [comment]
@dedenbangkit , we have to copy all the configurations (dependency etc too) .
First priority is copying of question group and the question it contains

**Comment by dedenbangkit** [comment]
- When Copying Question Group: Dependency will follows the question inside the question group if it's dependent inside the same question group, otherwise, just copy.
- `Paste here` button function should be disabled in the place where its not possible to copy. We can reuse `Move here` button logic.
- We will copy all the fields, except for user defined ID.

Please confirm @joycarpediem ?

**Comment by joycarpediem** [comment]
Sounds good.
However @wayangalihpratama , do note that this is in the product backlog. Please work first on the sprint backlog items before moving to this one
